version: '3.1'

services:
  db:
    image: postgres:15.2
    container_name: postgres-serv
    restart: always
    volumes:
      - ./volumens:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example
    